### ISSUE TITLE
Again not loading...

### ISSUE THREAD

**Issue by bobhenl** [nahkd123/Endrex#11]
Hi, plugin is again not loading... couldn't you somehow prevent it when new version is released?
```
>.... [01:49:23 INFO]: Paper v1_16_R1
>.... [01:49:23 INFO]: CS-CoreLib vDEV - 88 (git 6a39a9e7)
>.... [01:49:23 INFO]: Slimefun vDEV - 621 (git f50d1d2f)
>.... [01:49:23 INFO]: Metrics build: #14
>.... [01:49:23 INFO]:
>.... [01:49:23 INFO]: Installed Addons: (22)
>.... [01:49:23 INFO]: DyedBackpacks vDEV - 9 (git c42435c1)
>.... [01:49:23 INFO]: ExtraTools vDEV - 18 (git 634462af)
>.... [01:49:23 INFO]: SlimefunOreChunks vDEV - 9 (git 88dd72b0)
>.... [01:49:23 INFO]: Residence v4.9.1.6
>.... [01:49:23 INFO]: EcoPower vDEV - 1 (git 53445ee5)
>.... [01:49:23 INFO]: HotbarPets vDEV - 30 (git a434e3aa)
>.... [01:49:23 INFO]: ExtraGear vDEV - 11 (git 2682d2a4)
>.... [01:49:23 INFO]: SlimefunLuckyBlocks vDEV - 27 (git 2798a937)
>.... [01:49:23 INFO]: ExoticGarden vDEV - 56 (git e7024e9a)
>.... [01:49:23 INFO]: Barrels vDEV - 12 (git 0f66f4c9)
>.... [01:49:23 INFO]: ClayTech v1.2.4
>.... [01:49:23 INFO]: Endrex v1.0.3-b1
>.... [01:49:23 INFO]: ElectricSpawners vDEV - 17 (git 4ce66b94)
>.... [01:49:23 INFO]: LiteXpansion vDEV - 48 (git 47e9eec9)
>.... [01:49:23 INFO]: SoulJars vDEV - 16 (git 36dce719)
>.... [01:49:23 INFO]: MobCapturer vDEV - 10 (git 33cdceb3)
>.... [01:49:23 INFO]: SlimyTreeTaps vDEV - 14 (git b97239fb)
>.... [01:49:23 INFO]: PrivateStorage vDEV - 13 (git fa5cc2f9)
>.... [01:49:23 INFO]: ColoredEnderChests vDEV - 16 (git c987c764)
>.... [01:49:23 INFO]: TranscEndence vDEV - 17 (git 056982d3)
>.... [01:49:23 INFO]: CMI v8.7.5.3
>.... [01:49:23 INFO]: ChestTerminal vDEV - 34 (git 5f73deb7
```
```
[01:43:43] [Server thread/ERROR]: Error occurred while enabling Endrex v1.0.3-b1 (Is it up to date?)
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:194) ~[?:?]
	at java.lang.invoke.CallSite.makeSite(CallSite.java:315) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:259) ~[?:?]
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:249) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.items.misc.EndRespawnAnchor.<init>(EndRespawnAnchor.java:37) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.initInterestingThings(EndrexItems.java:363) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.init(EndrexItems.java:97) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.Endrex.onEnable(Endrex.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-131]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-131]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-131]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.invoke.LambdaConversionException: Functional interface io.github.thebusybiscuit.slimefun4.core.handlers.BlockPlaceHandler is not an interface
	at java.lang.invoke.AbstractValidatingLambdaMetafactory.<init>(AbstractValidatingLambdaMetafactory.java:178) ~[?:?]
	at java.lang.invoke.InnerClassLambdaMetafactory.<init>(InnerClassLambdaMetafactory.java:159) ~[?:?]
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:323) ~[?:?]
	at java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127) ~[?:?]
	... 17 more
```

**Comment by bobhenl** [comment]
@nahkd123

**Comment by nahkd123** [comment]
For now you can clone the repo to your computer and build it manually every time a new version of Slimefun comes out. I'll release new build soon after checked everything.

**Comment by nahkd123** [comment]
Just recently published Endrex v1.0.3 build 2. You can download it at https://github.com/nahkd123/Endrex/releases/tag/v1.0.3-b2

If there's any error printing on the console, please send the log so I can fix them.

Edit: Actually, there's a changes in the Slimefun source code, so I have to update my plugin again. Here is the v1.0.4: https://github.com/nahkd123/Endrex/releases/tag/v1.0.4-b1

**Comment by bobhenl** [comment]
@nahkd123 
```
[20:29:00] [Server thread/ERROR]: Error occurred while enabling Endrex v1.0.3-b2 (Is it up to date?)
java.lang.Error: Unresolved compilation problem: 
	The target type of this expression must be a functional interface

	at me.nahkd.spigot.sfaddons.endrex.items.misc.EndRespawnAnchor.<init>(EndRespawnAnchor.java:37) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.initInterestingThings(EndrexItems.java:363) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.init(EndrexItems.java:97) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.Endrex.onEnable(Endrex.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-133]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-133]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-133]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by nahkd123** [comment]
> @nahkd123
> 
> ```
> [20:29:00] [Server thread/ERROR]: Error occurred while enabling Endrex v1.0.3-b2 (Is it up to date?)
> java.lang.Error: Unresolved compilation problem: 
> 	The target type of this expression must be a functional interface
> 
> 	at me.nahkd.spigot.sfaddons.endrex.items.misc.EndRespawnAnchor.<init>(EndRespawnAnchor.java:37) ~[?:?]
> 	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.initInterestingThings(EndrexItems.java:363) ~[?:?]
> 	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.init(EndrexItems.java:97) ~[?:?]
> 	at me.nahkd.spigot.sfaddons.endrex.Endrex.onEnable(Endrex.java:78) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-133]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-133]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-133]
> 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-133]
> 	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-133]
> 	at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:471) ~[patched_1.16.1.jar:git-Paper-133]
> 	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.1.jar:git-Paper-133]
> 	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-133]
> 	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-133]
> 	at java.lang.Thread.run(Thread.java:832) [?:?]
> ```

Look like you're using v1.0.3-b2. Have you tried v1.0.4 yet?

**Comment by bobhenl** [comment]
Thanks, I didn't see it. BTW maybe you can start rewriting until next version of SF is out and broke it again :P :D @nahkd123
