### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by bobhenl** [nahkd123/Endrex#4]
## Description (Required)
I'm getting error in log.

## Steps to reproduce the Issue (Required)
Enable server

## Expected behavior (Required)
Any error in Console and log

## Server Log / Error Report
`[02:56:26] [Server thread/ERROR]: Error occurred while enabling Endrex v1.0.1 (Is it up to date?)
java.lang.NoSuchFieldError: MAGIC_EYE_OF_ENDER
	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.initInterestingThings(EndrexItems.java:369) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.init(EndrexItems.java:97) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.Endrex.onEnable(Endrex.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-301]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-301]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-301]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

## Environment (Required)
[03:14:27 INFO]: Paper v1_15_R1
[03:14:27 INFO]:
[03:14:27 INFO]: CS-CoreLib vDEV - 85 (git 4a7fce52)
[03:14:27 INFO]: Slimefun vDEV - 508 (git af09dcdb)
[03:14:27 INFO]:
[03:14:27 INFO]: Installed Addons (20)
[03:14:27 INFO]: DyedBackpacks vDEV - 5 (git 129670c7)
[03:14:27 INFO]: ExtraTools vDEV - 14 (git a330a3dd)
[03:14:27 INFO]: SoundMuffler vDEV - 11 (git eb3f26f8)
[03:14:27 INFO]: SlimefunOreChunks vDEV - 8 (git 41e31ffc)
[03:14:27 INFO]: HotbarPets vDEV - 27 (git 975a8997)
[03:14:27 INFO]: ExtraGear vDEV - 9 (git e851d81d)
[03:14:27 INFO]: SlimefunLuckyBlocks vDEV - 19 (git 9dbab303)
[03:14:27 INFO]: ExoticGarden vDEV - 46 (git fe5109fe)
[03:14:27 INFO]: Barrels vDEV - 11 (git abecba9c)
[03:14:27 INFO]: ClayTech v1.2.0-pre3
[03:14:27 INFO]: Endrex v1.0.1
[03:14:27 INFO]: ElectricSpawners vDEV - 12 (git 4ae47f83)
[03:14:27 INFO]: LiteXpansion vDEV - 30 (git 4f4ddd6b)
[03:14:27 INFO]: SoulJars vDEV - 16 (git 36dce719)
[03:14:27 INFO]: MobCapturer vDEV - 7 (git b61d3fbf)
[03:14:27 INFO]: SlimyTreeTaps vDEV - 11 (git b64db511)
[03:14:27 INFO]: PrivateStorage vDEV - 11 (git b064863b)
[03:14:27 INFO]: TranscEndence vDEV - 8 (git 45d671f3)
[03:14:27 INFO]: ColoredEnderChests vDEV - 12 (git 8dbdc909)
[03:14:27 INFO]: ChestTerminal vDEV - 30 (git 04393688)

 - Minecraft Version: 1.15.2
 - CS-CoreLib Version: vdev85
 - Slimefun Version: vdev 508
 - Plugin Version: v1.0.1

**Comment by nahkd123** [comment]
This error seem like only cause by auto update feature from Slimefun, when it's trying to replace itself with new jar file. Try to restart the server, but this time with latest version, so you can prevent Slimefun from updating itself.

**Comment by bobhenl** [comment]
And what's wrong on auto update? 

And I restarted it so many times and error is there still :D

**Comment by bobhenl** [comment]
PS: Continues with  Magic eye of ender. And auto-update in SlimeFun and Endrex is disabled....
```
[01:31:14 INFO]: [Endrex] Enabling Endrex v1.0.1
[01:31:14 WARN]: [Endrex] Could not save config.yml to plugins/Endrex/config.yml because config.yml already exists.
[01:31:14 INFO]: [Endrex] Loading schematics...
[01:31:14 INFO]: Loading structures/village0/house0.nsm from jar file...
[01:31:14 INFO]: Loading structures/village0/central.nsm from jar file...
[01:31:14 INFO]: Loading structures/magictree/0.nsm from jar file...
[01:31:15 INFO]: Loading structures/magictree/1.nsm from jar file...
[01:31:15 INFO]: Loading structures/magictree/2.nsm from jar file...
[01:31:15 INFO]: Loading structures/magictree/3.nsm from jar file...
[01:31:15 INFO]: Loading structures/other/SpongePowered.nsm from jar file...
[01:31:15 INFO]: Loading structures/other/mysterybox.nsm from jar file...
[01:31:15 ERROR]: Error occurred while enabling Endrex v1.0.1 (Is it up to date?)
java.lang.NoSuchFieldError: MAGIC_EYE_OF_ENDER
at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.initInterestingThings(EndrexItems.java:369) ~[?:?]
at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.init(EndrexItems.java:97) ~[?:?]
at me.nahkd.spigot.sfaddons.endrex.Endrex.onEnable(Endrex.java:78) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-325]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-325]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-325]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-325]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-325]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-325]
at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-325]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:900) ~[patched_1.15.2.jar:git-Paper-325]
at java.lang.Thread.run(Thread.java:832) [?:?]
[01:31:15 INFO]: [Endrex] Disabling Endrex v1.0.1
```

**Comment by nahkd123** [comment]
Ok, I'll check my plugin again when I came home. It must be because of some changes from new Slimefun version.

**Comment by nahkd123** [comment]
Hello, I'm back.

Yes it's probably because of the changes from Slimefun, so I have to rebuild Endrex. You can download this build in [here](https://github.com/nahkd123/Endrex/releases/tag/v1.0.1-b2). Just recently on Slimefun vDEV 523.

If there's no error shown on the console, you can close this issue.

**Comment by bobhenl** [comment]
And could you fix also this somehow?
```
[19:37:31 INFO]: [Endrex] Enabling Endrex v1.0.1-b2
[19:37:31 WARN]: [Endrex] Could not save config.yml to plugins/Endrex/config.yml because config.yml already exists.
[19:37:31 INFO]: [Endrex] Loading schematics...
[19:37:31 INFO]: Loading structures/village0/house0.nsm from jar file...
[19:37:31 INFO]: Loading structures/village0/central.nsm from jar file...
[19:37:31 INFO]: Loading structures/magictree/0.nsm from jar file...
[19:37:31 INFO]: Loading structures/magictree/1.nsm from jar file...
[19:37:31 INFO]: Loading structures/magictree/2.nsm from jar file...
[19:37:31 INFO]: Loading structures/magictree/3.nsm from jar file...
[19:37:31 INFO]: Loading structures/other/SpongePowered.nsm from jar file...
[19:37:31 INFO]: Loading structures/other/mysterybox.nsm from jar file...
[19:37:31 INFO]: [Endrex] Plugin enabled in 81ms
```

To don't turn off auto updater?

**Comment by nahkd123** [comment]
wdym? Endrex does not using auto updater at this time (well I guess I should add that feature in next version).

Also, the second line indicates that ``config.yml`` already exists, not an error.

And it seem like the plugin load just fine. I'll close this issue. If you have other issue (like found a bug or having a question), you should create new one.
