### ISSUE TITLE
The newest version of SlimeFun

### ISSUE THREAD

**Issue by bobhenl** [nahkd123/Endrex#8]
## Description (Required)
Error in log. The plugin doesn't enable probably due to new version of SlimeFun.

## Steps to reproduce the Issue (Required)
Install the newest version of SlimeFun.

## Expected behavior (Required)
It should load normally.

## Server Log / Error Report
```
[22:13:56] [Server thread/ERROR]: Error occurred while enabling Endrex v1.0.1-b2 (Is it up to date?)
java.lang.NoSuchMethodError: 'java.lang.String me.mrCookieSlime.Slimefun.api.SlimefunItemStack.getItemID()'
	at me.nahkd.spigot.sfaddons.endrex.items.resources.EndrexResourceItem.<init>(EndrexResourceItem.java:27) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.initResources(EndrexItems.java:182) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.items.EndrexItems.init(EndrexItems.java:84) ~[?:?]
	at me.nahkd.spigot.sfaddons.endrex.Endrex.onEnable(Endrex.java:78) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-353]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-353]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-353]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-353]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-353]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-353]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[22:13:56] [Server thread/INFO]: [Endrex] Disabling Endrex v1.0.1-b2
[22:13:56] [Server thread/INFO]: [Endrex] Plugin disabled in 0ms

```
## Environment (Required)

- Minecraft Version: 1.15.2
- CS-CoreLib Version: 85
- Slimefun Version: 544
- Plugin Version: v1.0.1-b2

**Comment by nahkd123** [comment]
It's appear that the letter "D" in the new version of Slimefun has been changed (to lowercase d). I'll update the code as soon as I have computer access.

**Comment by bobhenl** [comment]
Hi, how it looks @nahkd123

**Comment by Volgeop** [comment]
and does it supports 1.16 too?

**Comment by bobhenl** [comment]
and does it supports 1.16 too? @nahkd123

**Comment by nahkd123** [comment]
Hello, sorry for long delay, but Endrex v1.0.2 is now available and you can download it at https://github.com/nahkd123/Endrex/releases/tag/v1.0.2-b1

I haven't tested in 1.16 yet, but I'm sure that it will works just fine.
